#!/usr/bin/env python3
"""
HTTP Server Module
Handles communication with Chrome extension
"""

import json
import os
import time
from threading import Thread
from http.server import HTTPServer, BaseHTTPRequestHandler


def save_cookies_from_extension(cookies_string, platform='unknown'):
    """
    Save cookies from extension to cookies/[platform]Cookies.txt file
    Converts browser cookie string to Netscape format
    """
    if not cookies_string or cookies_string.strip() == '':
        return

    try:
        script_dir = os.path.dirname(os.path.abspath(__file__))
        
        # Create 'cookies' directory if it doesn't exist
        cookies_dir = os.path.join(script_dir, 'cookies')
        os.makedirs(cookies_dir, exist_ok=True)

        cookies_file = os.path.join(cookies_dir, f'{platform}Cookies.txt')

        # Parse cookie string (format: "name1=value1; name2=value2; ")
        cookie_pairs = cookies_string.split(';')

        # Determine domain based on platform
        domain_map = {
            'youtube': '.youtube.com',
            'facebook': '.facebook.com',
            'tiktok': '.tiktok.com',
            'instagram': '.instagram.com'
        }
        domain = domain_map.get(platform, '') # Default to empty if platform not found

        if not domain:
            print(f"[Server] Warning: Unknown platform '{platform}'. Cookies will be saved without a specific domain.")


        # Write in Netscape format
        with open(cookies_file, 'w', encoding='utf-8') as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# This file was generated by the Chrome extension\n")
            f.write(f"# Last updated: {time.strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write(f"# Platform: {platform}\n\n")

            for pair in cookie_pairs:
                pair = pair.strip()
                if '=' in pair:
                    name, value = pair.split('=', 1)
                    name = name.strip()
                    value = value.strip()

                    if name and value:
                        # Netscape format: domain, flag, path, secure, expiration, name, value
                        # Using a far future expiration date
                        expiration = int(time.time()) + (365 * 24 * 60 * 60)  # 1 year
                        f.write(f"{domain}\tTRUE\t/\tFALSE\t{expiration}\t{name}\t{value}\n")

        print(f"[Server] Saved {platform} cookies to {cookies_file} ({len([p for p in cookie_pairs if '=' in p])} cookies)")

    except Exception as e:
        print(f"[Server] Failed to save cookies for platform {platform}: {e}")


class ExtensionRequestHandler(BaseHTTPRequestHandler):
    """HTTP request handler for Chrome extension communication"""
    app_instance = None

    def do_GET(self):
        """Handle GET requests (health check)"""
        if self.path == '/health' or self.path == '/':
            self.send_response(200)
            self.send_header('Content-type', 'application/json')
            self.send_header('Access-Control-Allow-Origin', '*')
            self.end_headers()
            response = json.dumps({'status': 'ok', 'message': 'YouTube & Facebook Downloader is running'})
            self.wfile.write(response.encode())
        else:
            self.send_response(404)
            self.end_headers()

    def do_POST(self):
        """Handle POST requests from Chrome extension"""
        if self.path == '/download':
            content_length = int(self.headers['Content-Length'])
            post_data = self.rfile.read(content_length)

            try:
                data = json.loads(post_data.decode('utf-8'))
                url = data.get('url')
                quality = data.get('quality', '720p')
                download_playlist = data.get('downloadPlaylist', True)
                cookies = data.get('cookies', '')
                platform = data.get('platform', 'youtube')

                # Save cookies from extension to cookies.txt file
                if cookies:
                    save_cookies_from_extension(cookies, platform)

                # Send to main app
                if ExtensionRequestHandler.app_instance:
                    ExtensionRequestHandler.app_instance.handle_extension_download(
                        url, quality, download_playlist
                    )

                # Send success response
                self.send_response(200)
                self.send_header('Content-type', 'application/json')
                self.send_header('Access-Control-Allow-Origin', '*')
                self.end_headers()
                response = json.dumps({'status': 'success', 'message': 'Download started'})
                self.wfile.write(response.encode())

            except Exception as e:
                self.send_response(500)
                self.send_header('Content-type', 'application/json')
                self.send_header('Access-Control-Allow-Origin', '*')
                self.end_headers()
                response = json.dumps({'status': 'error', 'message': str(e)})
                self.wfile.write(response.encode())
        else:
            self.send_response(404)
            self.end_headers()

    def do_OPTIONS(self):
        """Handle OPTIONS requests for CORS"""
        self.send_response(200)
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Methods', 'POST, OPTIONS')
        self.send_header('Access-Control-Allow-Headers', 'Content-Type')
        self.end_headers()

    def log_message(self, format, *args):
        """Suppress default logging"""
        pass


class HTTPServerThread(Thread):
    """Thread to run HTTP server for extension communication"""
    def __init__(self, app_instance=None, port=8765):
        super().__init__(daemon=True)
        self.port = port
        self.server = None
        if app_instance:
            ExtensionRequestHandler.app_instance = app_instance

    def run(self):
        """Start HTTP server"""
        try:
            self.server = HTTPServer(('localhost', self.port), ExtensionRequestHandler)
            print(f"HTTP server started on port {self.port}")
            self.server.serve_forever()
        except Exception as e:
            print(f"Failed to start HTTP server: {e}")

    def stop(self):
        """Stop HTTP server"""
        if self.server:
            self.server.shutdown()
